'use client'

import { useState, useRef, useEffect } from 'react'
import { useReactToPrint } from 'react-to-print'
import { CreateResumeHeader } from '@/components/create-resume/CreateResumeHeader'
import { ResumeTypeSelector } from '@/components/create-resume/ResumeTypeSelector'
import { ProfileView } from '@/components/profile/ProfileView'
import { useRouter, useSearchParams } from 'next/navigation'
import { CompanyDetailsSection } from '@/components/create-resume/CompanyDetailsSection'
import { CreateResumeSidebar } from '@/components/create-resume/CreateResumeSidebar'
import { HowItWorks } from '@/components/create-resume/HowItWorks'
import { WorkspaceSection } from '@/components/create-resume/WorkspaceSection'
import { RegenerateSummaryModal } from '@/components/create-resume/RegenerateSummaryModal'
import { ManualEditModal } from '@/components/create-resume/ManualEditModal'
import { PersonalInfoForm } from '@/components/profile/PersonalInfoForm'
import { EmploymentForm } from '@/components/profile/EmploymentForm'
import { EducationForm } from '@/components/profile/EducationForm'
import { SkillsForm } from '@/components/profile/SkillsForm'
import { ProjectsForm } from '@/components/profile/ProjectsForm'
import { CertificationsForm } from '@/components/profile/CertificationsForm'
import { Button } from '@/components/ui/Button'
import { ArrowRight, ArrowLeft, Loader2, Download, ZoomIn, ZoomOut, FileText, Sparkles } from 'lucide-react'
import { TemplateSelector } from '@/components/create-resume/TemplateSelector'
import { ATSScoreMeter } from '@/components/create-resume/ATSScoreMeter'
import { AIGenerationLoadingHUD } from '@/components/create-resume/AIGenerationLoadingHUD'
import { getTemplateById, DEFAULT_TEMPLATE_ID } from '@/components/create-resume/templates/registry'
import { downloadResumeDocx } from '@/components/create-resume/exportDocx'
import { isPremiumPlan } from '@/utils/pricingPlans'
import { createClient } from '@/utils/supabase/client'
import { logUsageEvent } from '@/utils/logUsageEvent'
import { toast } from 'react-hot-toast'
import { Modal } from '@/components/ui/Overlay'
import { useUIStore } from '@/store/useUIStore'
import Link from 'next/link'

export default function CreateResumePage() {
  const [step, setStep] = useState(1)
  const [isGenerating, setIsGenerating] = useState(false)
  const [orchestratorState, setOrchestratorState] = useState<string>('')
  const [resumeZoom, setResumeZoom] = useState(1)
  const [autoScale, setAutoScale] = useState<number>(0.72)

  const [resumeType, setResumeType] = useState<'fulltime' | 'c2c'>('fulltime')
  const [selectedTemplateId, setSelectedTemplateId] = useState(DEFAULT_TEMPLATE_ID)
  const [profileData, setProfileData] = useState<any>({})
  const [editingTab, setEditingTab] = useState<string | null>(null)
  const router = useRouter()

  // Data generated by the AI
  const [generatedResume, setGeneratedResume] = useState<any>(null)
  const [interviewPrep, setInterviewPrep] = useState<any>(null)
  const [atsData, setAtsData] = useState<any>(null)
  const [currentResumeId, setCurrentResumeId] = useState<string | null>(null)

  const [isRegenerateSummaryModalOpen, setIsRegenerateSummaryModalOpen] = useState(false)
  const [isManualEditModalOpen, setIsManualEditModalOpen] = useState(false)
  const [isDownloadingDocx, setIsDownloadingDocx] = useState(false)

  const openModal = useUIStore((s) => s.openModal)
  const closeModal = useUIStore((s) => s.closeModal)

  const resumeRef = useRef<HTMLDivElement>(null)
  const canvasContainerRef = useRef<HTMLDivElement>(null)

  // Scroll to top when step changes
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }, [step])

  useEffect(() => {
    if (step !== 2 && step !== 3) return
    const updateScale = () => {
      if (canvasContainerRef.current) {
        const availableWidth = canvasContainerRef.current.clientWidth - 32
        if (availableWidth > 0) {
          const scale = Math.min(1, Math.max(0.4, Number((availableWidth / 814).toFixed(2))))
          setAutoScale(scale)
        }
      }
    }
    const timeoutId = setTimeout(updateScale, 60)
    window.addEventListener('resize', updateScale)
    
    let ro: ResizeObserver | null = null
    if (canvasContainerRef.current) {
      ro = new ResizeObserver(updateScale)
      ro.observe(canvasContainerRef.current)
    }

    return () => {
      clearTimeout(timeoutId)
      window.removeEventListener('resize', updateScale)
      if (ro) ro.disconnect()
    }
  }, [step, generatedResume])

  const reactToPrintFn = useReactToPrint({
    contentRef: resumeRef,
    documentTitle: `${(profileData?.full_name || 'Resume').replace(/\s+/g, '_')}_Tailored_Resume`,
    onAfterPrint: () => logUsageEvent(currentResumeId, 'pdf_download'),
  })

  const handlePrint = () => {
    if (!generatedResume || !resumeRef.current) {
      toast.error('No resume data available to export.')
      return
    }
    reactToPrintFn()
  }

  const handleDownloadDocx = async () => {
    if (!generatedResume) {
      toast.error('No resume data to export yet.')
      return
    }
    setIsDownloadingDocx(true)
    try {
      const fileName = `${(profileData?.full_name || 'Resume').replace(/\s+/g, '_')}_Resume.docx`
      await downloadResumeDocx(generatedResume, profileData, fileName)
      logUsageEvent(currentResumeId, 'docx_download')
    } catch (error) {
      console.error('DOCX export failed:', error)
      toast.error('Failed to generate DOCX. Please try again.')
    } finally {
      setIsDownloadingDocx(false)
    }
  }

  const searchParams = useSearchParams()
  const resumeIdParam = searchParams?.get('id')

  useEffect(() => {
    // Fetch user profile on mount
    const fetchProfile = async () => {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        const { data } = await supabase.from('profiles').select('*').eq('id', user.id).single()
        if (data) setProfileData(data)
      }
    }
    fetchProfile()
  }, [])

  useEffect(() => {
    if (!resumeIdParam) return

    const loadExistingResume = async () => {
      try {
        const supabase = createClient()
        const { data: resume, error: resumeErr } = await supabase
          .from('resumes_v2')
          .select('*')
          .eq('id', resumeIdParam)
          .single()

        if (resumeErr || !resume) {
          console.error('Failed to load resume:', resumeErr)
          return
        }

        setCurrentResumeId(resume.id)
        const isC2C = String(resume.resume_type || '').toLowerCase().includes('c2c')
        setResumeType(isC2C ? 'c2c' : 'fulltime')
        setSelectedTemplateId(isC2C ? 'c2c' : 'modern')

        // Fetch resume sections
        const { data: sections } = await supabase
          .from('resume_sections')
          .select('section_type, content')
          .eq('resume_id', resume.id)

        if (sections && sections.length > 0) {
          const reconstructed: any = {
            summary: [],
            skills: [],
            experience: [],
            education: [],
            certifications: []
          }
          sections.forEach((sec: any) => {
            const key = sec.section_type.toLowerCase()
            reconstructed[key] = sec.content
          })
          setGeneratedResume(reconstructed)
        }

        // Fetch ATS analysis
        const { data: ats } = await supabase
          .from('ats_analyses')
          .select('*')
          .eq('resume_id', resume.id)
          .order('created_at', { ascending: false })
          .limit(1)
          .maybeSingle()

        if (ats) {
          setAtsData({
            overallScore: ats.overall_score,
            categoryScores: ats.category_scores,
            missingKeywords: ats.missing_keywords,
            improvementSuggestions: ats.improvement_suggestions
          })
        }

        // Fetch Interview Prep
        const { data: prep } = await supabase
          .from('interview_preparations')
          .select('*')
          .eq('resume_id', resume.id)
          .order('created_at', { ascending: false })
          .limit(1)
          .maybeSingle()

        if (prep) {
          setInterviewPrep({
            hrQuestions: prep.hr_questions,
            techQuestions: prep.tech_questions,
            starAnswers: prep.star_answers,
            selfIntroduction: prep.self_introduction,
            companyNotes: prep.company_notes
          })
        }

        setStep(2)
      } catch (err) {
        console.error('Error loading resume:', err)
      }
    }

    loadExistingResume()
  }, [resumeIdParam])

  const handleGenerate = async (companyName: string, jobRole: string, jobDescription: string) => {
    setIsGenerating(true)
    setOrchestratorState('Parsing Job Description...')
    try {
      // 1. Parse JD
      const parseRes = await fetch('/api/ai/parse-jd', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ companyName, jobRole, jobDescription })
      })
      const parseData = await parseRes.json()
      if (!parseData.success) throw new Error(parseData.error || 'Failed to parse JD')

      setOrchestratorState('Building Resume Strategy...')
      // 2. Generate Strategy
      const strategyRes = await fetch('/api/ai/generate-strategy', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ parsedJdData: parseData.parsed_data, masterProfile: profileData, parsedJdId: parseData.parsed_jd_id })
      })
      const strategyData = await strategyRes.json()
      if (!strategyData.success) throw new Error(strategyData.error || 'Failed to generate strategy')

      setOrchestratorState('Generating Resume Content...')
      // 3. Generate Resume
      const rType = resumeType === 'c2c' ? 'C2C (Contract to Hire)' : 'Full Time'
      const resumeRes = await fetch('/api/ai/generate-resume', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          masterProfile: profileData,
          parsedJdData: parseData.parsed_data,
          strategyData: strategyData.strategy_data,
          resumeType: rType,
          parsedJdId: parseData.parsed_jd_id,
          strategyId: strategyData.strategy_id,
          title: `${rType} Resume - ${companyName}`
        })
      })
      const resumeGenData = await resumeRes.json()

      // Handle Paywall or generation error
      if (!resumeGenData.success) {
        if (resumeGenData.error === 'Paywall') {
          throw new Error('Paywall');
        }
        throw new Error(resumeGenData.message || resumeGenData.error || 'Failed to generate resume')
      }

      setCurrentResumeId(resumeGenData.resume_id)
      setGeneratedResume(resumeGenData.generated_resume)

      setOrchestratorState('Finalizing ATS Analysis & Prep...')
      // 4. Generate ATS & Prep concurrently
      const [atsRes, prepRes] = await Promise.all([
        fetch('/api/ai/analyze-ats', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            parsedJdData: parseData.parsed_data,
            generatedResume: resumeGenData.generated_resume,
            resumeId: resumeGenData.resume_id
          })
        }),
        fetch('/api/ai/generate-prep', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            parsedJdData: parseData.parsed_data,
            generatedResume: resumeGenData.generated_resume,
            resumeId: resumeGenData.resume_id
          })
        })
      ])

      const atsDataRes = await atsRes.json()
      const prepDataRes = await prepRes.json()

      if (atsDataRes.success) setAtsData(atsDataRes.analysis)
      if (prepDataRes.success) setInterviewPrep(prepDataRes.prep)

      // Keep user on Step 2 to display the generated resume preview immediately
      setStep(2)
      toast.success('Tailored resume generated successfully!')
    } catch (error: any) {
      console.error('Generation failed:', error)
      if (error.message === 'Paywall') {
        openModal('paywall-modal')
      } else {
        toast.error(`Failed to generate resume: ${error.message || error}`)
      }
    } finally {
      setIsGenerating(false)
      setOrchestratorState('')
    }
  }

  const applyBaseResumeFallback = () => {
    if (!generatedResume || !profileData || !profileData.master_resume_data?.employment) {
      toast.error('No base employment data found.');
      return;
    }

    // Clone the generated resume
    const newResume = { ...generatedResume };

    // Keep the first 2 projects from AI
    const aiProjects = newResume.experience.slice(0, 2);

    // Map the older projects from original profile data
    const baseProjects = profileData.master_resume_data.employment.slice(2).map((exp: any) => {
      let durationStr = exp.startDate || '';
      if (exp.current) durationStr += ' - Present';
      else if (exp.endDate) durationStr += ` - ${exp.endDate}`;

      return {
        id: exp.id || '',
        role: exp.title || '',
        company: exp.company || '',
        duration: durationStr,
        bullets: exp.responsibilities ? exp.responsibilities.split('\n').map((s: string) => s.trim()).filter(Boolean) : [],
        environment: []
      };
    });

    newResume.experience = [...aiProjects, ...baseProjects];
    setGeneratedResume(newResume);
    toast.success('Restored older roles to original base data');
  };

  const handleRegenerateSummary = async (firstPoint: string) => {
    try {
      const res = await fetch('/api/ai/regenerate-summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          masterProfile: profileData,
          resumeType: resumeType === 'c2c' ? 'C2C (Contract to Hire)' : 'Full Time',
          firstPoint,
          resumeId: currentResumeId
        })
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error);

      setGeneratedResume({
        ...generatedResume,
        summary: data.summary
      });
      toast.success('Summary regenerated successfully!');
    } catch (error: any) {
      console.error(error);
      toast.error('Failed to regenerate summary');
    }
  };

  const handleManualEditSave = (newSkills: any[]) => {
    setGeneratedResume({
      ...generatedResume,
      skills: newSkills
    });
    toast.success('Skills updated successfully!');
  };

  const handleLocalSave = (updatedProfile: any) => {
    setProfileData(updatedProfile)
    setEditingTab(null)
  }

  const renderEditForm = () => {
    const commonProps = {
      profile: profileData,
      localMode: true,
      onLocalSave: handleLocalSave,
      onNext: () => setEditingTab(null), // just close form on "Save & Next" if they click it
      onCancel: () => setEditingTab(null),
      resumeType: resumeType
    }

    switch (editingTab) {
      case 'personal': return <PersonalInfoForm {...commonProps} />
      case 'employment': return <EmploymentForm {...commonProps} />
      case 'education': return <EducationForm {...commonProps} />
      case 'skills': return <SkillsForm {...commonProps} onFinalSave={handleLocalSave} />
      case 'projects': return <ProjectsForm {...commonProps} />
      case 'certifications': return <CertificationsForm {...commonProps} />
      default: return null
    }
  }

  return (
    <div className="px-8 pt-8 pb-8 max-w-[1600px] mx-auto min-h-screen bg-slate-50/50">
      <Modal id="paywall-modal" title="Upgrade to Pro" size="sm">
        <div className="flex flex-col items-center text-center pt-2">
          <div className="w-16 h-16 bg-orange-100 rounded-full flex items-center justify-center mb-4">
            <span className="text-2xl">🚀</span>
          </div>
          <h3 className="text-xl font-bold text-slate-900 mb-2">You've reached your limit!</h3>
          <p className="text-[13px] text-slate-500 mb-6 leading-relaxed">
            You have used all 20 of your free AI resume generations. Upgrade to our Pro plan to unlock unlimited resumes, cover letters, and advanced ATS optimization.
          </p>
          <div className="flex gap-3 w-full">
            <Button variant="outline" className="flex-1" onClick={() => closeModal('paywall-modal')}>
              Cancel
            </Button>
            <Link href="/dashboard/pricing" className="flex-1">
              <Button className="w-full">
                Upgrade Now
              </Button>
            </Link>
          </div>
        </div>
      </Modal>

      <CreateResumeHeader />

      <main className="mt-5">
        {/* Dynamic AI Generation Pipeline Stepper */}
        <HowItWorks currentStep={step} onStepClick={(s) => setStep(s)} />

        {step === 1 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex flex-col gap-6">
              <TemplateSelector
                selectedId={selectedTemplateId}
                onChange={setSelectedTemplateId}
                isSubscribed={isPremiumPlan(profileData?.plan_id)}
                onRequiresUpgrade={() => openModal('paywall-modal')}
                resumeType={resumeType}
              />
              <ResumeTypeSelector selectedType={resumeType} onChange={(type) => {
                setResumeType(type)
                // Automatically switch to the correct default template for the mode
                if (type === 'c2c') setSelectedTemplateId('c2c')
                else if (selectedTemplateId === 'c2c') setSelectedTemplateId('modern')
              }} />
              <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-8">
                <div className="mb-8 flex justify-between items-center">
                  <div>
                    <h2 className="text-[18px] font-black text-slate-900 mb-1">Resume Details</h2>
                    <p className="text-[13px] font-medium text-slate-500">Verify your profile information before generating your tailored resume</p>
                  </div>
                  {editingTab && (
                    <Button variant="outline" size="sm" onClick={() => setEditingTab(null)}>
                      Cancel Edit
                    </Button>
                  )}
                </div>

                {editingTab ? (
                  renderEditForm()
                ) : (
                  <ProfileView
                    profile={profileData}
                    hideBanner={true}
                    onEdit={(tab) => setEditingTab(tab)}
                  />
                )}
              </div>
            </div>

            <div className="flex justify-end pt-4">
              <Button
                onClick={() => setStep(2)}
                className="h-12 px-8 rounded-xl shadow-lg shadow-primary/20 hover:-translate-y-0.5 transition-all text-[15px]"
              >
                <div className="flex items-center gap-2">
                  Next Step: Job Details
                  <ArrowRight className="w-4 h-4" />
                </div>
              </Button>
            </div>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {!generatedResume ? (
              <>
                <div className="flex justify-between items-center bg-white p-4 rounded-2xl border border-slate-200 shadow-sm">
                  <Button
                    onClick={() => setStep(1)}
                    className="h-10 px-6 rounded-lg text-slate-600 hover:text-slate-900 hover:bg-slate-100 bg-transparent"
                    disabled={isGenerating}
                  >
                    <div className="flex items-center gap-2">
                      <ArrowLeft className="w-4 h-4" />
                      Back to Step 1
                    </div>
                  </Button>
                  <div className="text-[14px] font-bold text-slate-800">
                    Step 2 of 3: Target Job & Details
                  </div>
                  <div className="w-[130px]"></div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start">
                  <div className="w-full min-w-0 space-y-6 relative">
                    {isGenerating && (
                      <AIGenerationLoadingHUD currentState={orchestratorState} />
                    )}
                    <CompanyDetailsSection onGenerate={(company, role, jd) => handleGenerate(company, role, jd)} />
                  </div>

                  <div className="w-full min-w-0 space-y-6">
                    <CreateResumeSidebar />
                  </div>
                </div>
              </>
            ) : (
              <div className="space-y-3">
                {/* Unified Single-Row Action & Document Control Bar */}
                <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl py-2 px-3 sm:px-4 flex items-center justify-between gap-3 shadow-2xs shrink-0 whitespace-nowrap overflow-x-auto scrollbar-none">
                  
                  {/* Left Controls: Navigation, ATS Match & Template Info */}
                  <div className="flex items-center gap-2 shrink-0 whitespace-nowrap">
                    <Button
                      onClick={() => setGeneratedResume(null)}
                      className="h-8 px-3 rounded-lg text-slate-600 hover:text-slate-900 hover:bg-slate-100 bg-white border border-slate-200 cursor-pointer whitespace-nowrap shrink-0 shadow-2xs text-[11.5px] font-semibold"
                    >
                      <div className="flex items-center gap-1.5 whitespace-nowrap">
                        <ArrowLeft className="w-3.5 h-3.5" />
                        <span>Edit Job Details</span>
                      </div>
                    </Button>

                    {/* Real-time ATS Score Meter Pill */}
                    <div className="shrink-0 whitespace-nowrap">
                      <ATSScoreMeter atsData={atsData} variant="compact" />
                    </div>

                    <span className="text-slate-300 dark:text-slate-700 text-[12px] hidden md:inline shrink-0">•</span>
                    <span className="text-[11.5px] font-semibold text-emerald-700 bg-emerald-50 px-2.5 py-0.5 rounded-md border border-emerald-200/70 whitespace-nowrap hidden md:inline shrink-0">
                      {getTemplateById(selectedTemplateId).name} (A4)
                    </span>
                  </div>

                  {/* Right Controls: AI Quick Edits, Zoom Controls & Downloads */}
                  <div className="flex items-center gap-1.5 shrink-0 whitespace-nowrap">
                    <Button 
                      onClick={() => setIsRegenerateSummaryModalOpen(true)} 
                      variant="outline" 
                      className="h-8 px-2.5 rounded-lg border-slate-200 text-slate-700 bg-white shadow-2xs hover:bg-slate-50 text-[11.5px] font-semibold cursor-pointer whitespace-nowrap shrink-0"
                    >
                      Refine Summary
                    </Button>
                    <Button 
                      onClick={() => setIsManualEditModalOpen(true)} 
                      variant="outline" 
                      className="h-8 px-2.5 rounded-lg border-slate-200 text-slate-700 bg-white shadow-2xs hover:bg-slate-50 text-[11.5px] font-semibold cursor-pointer whitespace-nowrap shrink-0"
                    >
                      Edit Skills
                    </Button>

                    {/* Zoom Controls */}
                    <div className="flex items-center gap-0.5 bg-slate-100 dark:bg-slate-800 p-0.5 rounded-lg border border-slate-200 dark:border-slate-700 shrink-0">
                      <button
                        onClick={() => setResumeZoom(z => Math.max(Number((z - 0.1).toFixed(1)), 0.6))}
                        className="p-1 hover:bg-white dark:hover:bg-slate-700 rounded text-slate-600 dark:text-slate-300 hover:text-slate-900 transition-all cursor-pointer"
                        title="Zoom Out"
                      >
                        <ZoomOut className="w-3 h-3" />
                      </button>
                      <button
                        onClick={() => setResumeZoom(1)}
                        className="px-1.5 py-0.5 text-[11px] font-bold text-slate-700 dark:text-slate-300 hover:text-slate-900 transition-colors cursor-pointer whitespace-nowrap"
                        title="Reset to Fit Width"
                      >
                        {resumeZoom === 1 ? 'Fit' : `${Math.round(resumeZoom * 100)}%`}
                      </button>
                      <button
                        onClick={() => setResumeZoom(z => Math.min(Number((z + 0.1).toFixed(1)), 1.5))}
                        className="p-1 hover:bg-white dark:hover:bg-slate-700 rounded text-slate-600 dark:text-slate-300 hover:text-slate-900 transition-all cursor-pointer"
                        title="Zoom In"
                      >
                        <ZoomIn className="w-3 h-3" />
                      </button>
                    </div>

                    <Button 
                      onClick={handleDownloadDocx} 
                      disabled={isDownloadingDocx}
                      variant="outline" 
                      className="h-8 px-2.5 rounded-lg border-slate-200 text-slate-700 bg-white shadow-2xs hover:bg-slate-50 text-[11.5px] font-semibold cursor-pointer flex items-center gap-1.5 whitespace-nowrap shrink-0"
                    >
                      {isDownloadingDocx ? <Loader2 className="w-3 h-3 animate-spin text-emerald-600" /> : <FileText className="w-3 h-3 text-slate-500" />}
                      <span>Word (DOCX)</span>
                    </Button>
                    <Button 
                      onClick={handlePrint} 
                      className="h-8 px-3 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white shadow-xs text-[11.5px] font-bold cursor-pointer flex items-center gap-1.5 whitespace-nowrap shrink-0"
                    >
                      <Download className="w-3 h-3" />
                      <span>Download PDF</span>
                    </Button>
                  </div>
                </div>

                {/* Resume Workbench Canvas */}
                <div className="space-y-3">

                  {/* Document Canvas */}
                  <div 
                    ref={canvasContainerRef}
                    className="bg-slate-200/80 dark:bg-slate-950/80 p-3 sm:p-5 rounded-2xl border border-slate-300/80 dark:border-slate-800 flex flex-col items-center justify-start overflow-y-auto overflow-x-hidden h-[78vh] min-h-[580px] shadow-inner scrollbar-thin"
                  >
                    {(() => {
                      const effectiveScale = Number((autoScale * resumeZoom).toFixed(2))
                      const horizontalMargin = (794 * effectiveScale - 794) / 2
                      return (
                        <div 
                          className="flex justify-center transition-all duration-200 py-2 w-full"
                        >
                          <div 
                            style={{ 
                              transform: `scale(${effectiveScale})`, 
                              transformOrigin: 'top center',
                              width: '794px',
                              marginLeft: `${horizontalMargin}px`,
                              marginRight: `${horizontalMargin}px`,
                            }}
                          >
                            {(() => {
                              const SelectedTemplate = getTemplateById(selectedTemplateId).component
                              return <SelectedTemplate resumeData={generatedResume} profileData={profileData} />
                            })()}
                          </div>
                        </div>
                      )
                    })()}
                  </div>

                  {/* Bottom Next Step Callout */}
                  <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4 sm:p-5 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-sm">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center text-primary shrink-0">
                        <Sparkles className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className="text-[14px] font-bold text-slate-900 dark:text-slate-100">
                          Ready for Interview Prep & Application Strategy?
                        </h4>
                        <p className="text-[12px] text-slate-500 dark:text-slate-400">
                          Generate tailored Cover Letter, 60s Pitch, STAR Stories, Tech Q&A, and Salary Tips.
                        </p>
                      </div>
                    </div>

                    <Button
                      onClick={() => setStep(3)}
                      className="w-full sm:w-auto h-11 px-6 rounded-xl bg-primary hover:bg-primary/90 text-white shadow-md shadow-primary/20 text-[13.5px] font-bold cursor-pointer flex items-center justify-center gap-2"
                    >
                      <span>Proceed to Step 3: Interview Strategy</span>
                      <ArrowRight className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {step === 3 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Top Navigation Bar */}
            <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 bg-white p-4 sm:p-5 rounded-2xl border border-slate-200 shadow-sm">
              <div className="flex items-center gap-3">
                <Button
                  onClick={() => setStep(2)}
                  className="h-9 px-4 rounded-lg text-slate-600 hover:text-slate-900 hover:bg-slate-100 bg-transparent border border-slate-200 cursor-pointer"
                >
                  <div className="flex items-center gap-1.5 text-[13px] font-semibold">
                    <ArrowLeft className="w-3.5 h-3.5" />
                    Back to Resume Preview (Step 2)
                  </div>
                </Button>

                {/* Real-time ATS Score Meter Pill */}
                <ATSScoreMeter atsData={atsData} variant="compact" />
              </div>

              <div className="flex items-center gap-2">
                <span className="text-[14px] font-bold text-slate-900 hidden md:inline">
                  Step 3 of 3: Interview & Application Strategy Workspace
                </span>
              </div>

              <div className="flex items-center gap-2.5">
                <Button 
                  onClick={handleDownloadDocx} 
                  disabled={isDownloadingDocx}
                  variant="outline" 
                  className="h-9 px-3.5 rounded-lg border-slate-200 text-slate-700 bg-white shadow-2xs hover:bg-slate-50 text-[12.5px] font-semibold cursor-pointer flex items-center gap-1.5"
                >
                  {isDownloadingDocx ? <Loader2 className="w-3.5 h-3.5 animate-spin text-emerald-600" /> : <FileText className="w-3.5 h-3.5 text-slate-500" />}
                  Word (DOCX)
                </Button>
                <Button onClick={handlePrint} className="h-9 px-5 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm text-[13px] font-semibold cursor-pointer flex items-center gap-1.5">
                  <Download className="w-3.5 h-3.5" />
                  Download PDF
                </Button>
              </div>
            </div>

            {/* Dedicated Full-Width Interview & Application Strategy Workspace */}
            <div className="w-full">
              <WorkspaceSection 
                interviewPrep={interviewPrep} 
                atsData={atsData} 
                resumeId={currentResumeId} 
                candidateName={profileData?.full_name} 
              />
            </div>
          </div>
        )}

        {/* Modals for Step 3 fallbacks */}
        <RegenerateSummaryModal
          isOpen={isRegenerateSummaryModalOpen}
          onClose={() => setIsRegenerateSummaryModalOpen(false)}
          onRegenerate={handleRegenerateSummary}
        />
        <ManualEditModal
          isOpen={isManualEditModalOpen}
          onClose={() => setIsManualEditModalOpen(false)}
          onSave={handleManualEditSave}
          initialSkills={generatedResume?.skills || []}
        />

        {/* Dedicated Always-Mounted Print Target for 100% Reliable PDF Download across Steps 2 & 3 */}
        {generatedResume && (
          <div 
            aria-hidden="true"
            style={{
              position: 'absolute',
              left: '-99999px',
              top: 0,
              width: '794px',
              opacity: 0,
              pointerEvents: 'none',
              zIndex: -9999
            }}
          >
            {(() => {
              const PrintTemplate = getTemplateById(selectedTemplateId).component
              return (
                <div ref={resumeRef}>
                  <PrintTemplate 
                    resumeData={generatedResume} 
                    profileData={profileData} 
                  />
                </div>
              )
            })()}
          </div>
        )}
      </main>
    </div>
  )
}
