'use client'

import { useState, useRef, useEffect } from 'react'
import { useReactToPrint } from 'react-to-print'
import { CreateResumeHeader } from '@/components/create-resume/CreateResumeHeader'
import { ResumeTypeSelector } from '@/components/create-resume/ResumeTypeSelector'
import { PersonalInfoSection } from '@/components/create-resume/PersonalInfoSection'
import { CompanyDetailsSection } from '@/components/create-resume/CompanyDetailsSection'
import { CreateResumeSidebar } from '@/components/create-resume/CreateResumeSidebar'
import { HowItWorks } from '@/components/create-resume/HowItWorks'
import { WorkspaceSection } from '@/components/create-resume/WorkspaceSection'
import { DownloadSidebar } from '@/components/create-resume/DownloadSidebar'
import { Button } from '@/components/ui/Button'
import { ArrowRight, ArrowLeft, Loader2, Download } from 'lucide-react'
import { ResumeRenderer } from '@/components/create-resume/ResumeRenderer'
import { createClient } from '@/utils/supabase/client'

export default function CreateResumePage() {
  const [step, setStep] = useState(1)
  const [isGenerating, setIsGenerating] = useState(false)
  const [resumeType, setResumeType] = useState('C2C')
  const [profileData, setProfileData] = useState<any>({})
  
  // Data generated by the AI
  const [generatedResume, setGeneratedResume] = useState<any>(null)
  
  const resumeRef = useRef<HTMLDivElement>(null)
  
  const handlePrint = useReactToPrint({
    contentRef: resumeRef,
    documentTitle: 'My_Tailored_Resume',
  })

  useEffect(() => {
    // Fetch user profile on mount
    const fetchProfile = async () => {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        const { data } = await supabase.from('profiles').select('*').eq('id', user.id).single()
        if (data) setProfileData(data)
      }
    }
    fetchProfile()
  }, [])

  const handleGenerate = async (companyName: string, jobRole: string, jobDescription: string) => {
    setIsGenerating(true)
    try {
      // 1. Call Orchestrator
      const orchestratorRes = await fetch('/api/ai/orchestrator', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          masterProfile: profileData,
          companyName,
          jobRole,
          jobDescription,
          resumeType
        })
      })
      
      const data = await orchestratorRes.json()
      
      if (!data.success) throw new Error(data.error)
      
      // 2. Fetch the newly generated resume sections
      const supabase = createClient()
      const { data: sections } = await supabase.from('resume_sections').select('*').eq('resume_id', data.resume_id)
      
      if (sections) {
        // Construct the expected structure for ResumeRenderer
        const resume: any = {}
        sections.forEach((sec: any) => {
          resume[sec.section_type.toLowerCase()] = sec.content
        })
        setGeneratedResume(resume)
      }
      
      setStep(3)
    } catch (error) {
      console.error('Generation failed:', error)
      alert('Failed to generate resume. Please try again.')
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <div className="px-8 pb-8 max-w-[1600px] mx-auto min-h-screen bg-slate-50/50">
      <CreateResumeHeader />
      
      <main className="mt-8">
        {step === 1 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <HowItWorks />
            
            <div className="flex flex-col gap-6">
              <div onClick={() => setResumeType('C2C')}>
                 {/* Temporary wrapper just to show we capture state, ResumeTypeSelector should ideally accept props */}
                <ResumeTypeSelector />
              </div>
              <PersonalInfoSection />
            </div>

            <div className="flex justify-end pt-4">
              <Button 
                onClick={() => setStep(2)}
                className="h-12 px-8 rounded-xl shadow-lg shadow-primary/20 hover:-translate-y-0.5 transition-all text-[15px]"
              >
                <div className="flex items-center gap-2">
                  Next Step: Job Details
                  <ArrowRight className="w-4 h-4" />
                </div>
              </Button>
            </div>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex justify-between items-center bg-white p-4 rounded-2xl border border-slate-200 shadow-sm">
              <Button 
                onClick={() => setStep(1)}
                className="h-10 px-6 rounded-lg text-slate-600 hover:text-slate-900 hover:bg-slate-100 bg-transparent"
                disabled={isGenerating}
              >
                <div className="flex items-center gap-2">
                  <ArrowLeft className="w-4 h-4" />
                  Back to Step 1
                </div>
              </Button>
              <div className="text-[14px] font-bold text-slate-800">
                Step 2 of 3: Job Details
              </div>
              <div className="w-[130px]"></div>
            </div>

            <div className="flex flex-col xl:flex-row gap-6">
              <div className="flex-1 min-w-0 space-y-6 relative">
                {isGenerating && (
                  <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-50 flex flex-col items-center justify-center rounded-2xl border border-primary/20">
                    <Loader2 className="w-12 h-12 text-primary animate-spin mb-4" />
                    <h3 className="text-xl font-bold text-slate-900">AI Orchestrator is Running...</h3>
                    <p className="text-slate-500 font-medium mt-2">Parsing JD • Strategizing • Generating</p>
                  </div>
                )}
                {/* Note: In a real app we would capture form inputs here and pass to handleGenerate */}
                <CompanyDetailsSection onGenerate={() => handleGenerate('Example Corp', 'Senior Engineer', 'We need a senior engineer with React and Node.js experience...')} />
              </div>
              
              <div className="w-full xl:w-[400px] shrink-0 space-y-6">
                <CreateResumeSidebar />
              </div>
            </div>
          </div>
        )}

        {step === 3 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex justify-between items-center bg-white p-4 rounded-2xl border border-slate-200 shadow-sm">
              <Button 
                onClick={() => setStep(2)}
                className="h-10 px-6 rounded-lg text-slate-600 hover:text-slate-900 hover:bg-slate-100 bg-transparent"
              >
                <div className="flex items-center gap-2">
                  <ArrowLeft className="w-4 h-4" />
                  Back to Details
                </div>
              </Button>
              <div className="text-[14px] font-bold text-slate-800">
                Final Step: Review & Download
              </div>
              <Button onClick={handlePrint} className="h-10 px-6 rounded-lg bg-green-600 hover:bg-green-700 text-white shadow-md">
                <div className="flex items-center gap-2">
                  <Download className="w-4 h-4" />
                  Export to PDF
                </div>
              </Button>
            </div>

            <div className="flex flex-col xl:flex-row gap-6">
              <div className="flex-1 min-w-0 space-y-6">
                {/* Visual rendering of the actual resume */}
                {generatedResume ? (
                  <div className="overflow-x-auto pb-4">
                    <ResumeRenderer ref={resumeRef} resumeData={generatedResume} profileData={profileData} />
                  </div>
                ) : (
                  <div className="bg-white p-8 text-center rounded-2xl border border-slate-200">
                    No resume data found.
                  </div>
                )}
              </div>
              
              <div className="w-full xl:w-[400px] shrink-0 space-y-6">
                 {/* Interview Prep Pane */}
                <WorkspaceSection />
                <DownloadSidebar />
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}
